### ISSUE TITLE
Subfiles not being marked as 'read'. 

### ISSUE THREAD

**Issue by RockyCoon** [volundmush/mushcode#2] opened 2015-03-22 01:48 UTC
Subfiles of +help topics do not get marked as 'Read' (That Red Asterisk remains). 

Upgraded from an old version of Help System if that's any help.

**Comment by sceox** [comment] 2015-03-22 04:56
In `&INC`SHOW`Topic` there is a missing `%` on the `q<ann>` that is an argument to `FUN`HAVEREADSUB`. the function will always return a red \* because no matching attribute is found. So although I haven't tested this could be the cause.

**Comment by volundmush** [comment] 2015-03-22 18:11
Fixed in the latest commit.
That missing % -was- a problem. But also a problem:
INC`SHOW`SUB wasn't actually setting the read date at all for some reason.

**Closed as completed by volundmush** 2015-03-22 18:11 UTC
